# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('prim_key', models.CharField(max_length=577, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=512)),
                ('sectioned', models.BooleanField()),
                ('section_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=64)),
                ('collection', models.CharField(default='', max_length=512)),
                ('author', models.CharField(default='', max_length=128)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Instance',
            fields=[
                ('prim_key', models.CharField(max_length=2024, primary_key=True, serialize=False)),
                ('iteration', models.IntegerField(default=0)),
                ('native', models.CharField(max_length=64)),
                ('completed', models.BooleanField()),
                ('missing_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('prim_key', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('html_id', models.CharField(default='', max_length=20)),
                ('text', models.CharField(max_length=2048)),
                ('paragraph', models.IntegerField()),
                ('section', models.IntegerField(default=0)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polly.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book_instance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polly.Profile'),
        ),
        migrations.AddField(
            model_name='book_instance',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polly.Sentence'),
        ),
    ]
