# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_instance',
            name='sentence_chapters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='helper',
            field=models.CharField(default='', max_length=4),
        ),
    ]
